#include "unit_gen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#include <errno.h>

static int make_dir_p(const char *dir, mode_t mode) {
    char tmp[MAX_PATH_LEN];
    char *p = NULL;
    size_t len;

    snprintf(tmp, sizeof(tmp), "%s", dir);
    len = strlen(tmp);
    if (len == 0) return -1;
    if (tmp[len - 1] == '/') {
        tmp[len - 1] = 0;
    }

    for (p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = 0;
            if (mkdir(tmp, mode) != 0 && errno != EEXIST) {
                return -1;
            }
            *p = '/';
        }
    }
    if (mkdir(tmp, mode) != 0 && errno != EEXIST) {
        return -1;
    }
    return 0;
}

static bool is_valid_name(const char *name) {
    if (!name || !*name) return false;
    for (const char *p = name; *p; p++) {
        if (!isalnum((unsigned char)*p) && *p != '-' && *p != '_' && *p != '.') {
            return false;
        }
    }
    return true;
}

int unit_gen_get_dir(SystemdScope scope, char *out_path, size_t max_len) {
    if (!out_path || max_len == 0) return -1;

    if (scope == SCOPE_SYSTEM) {
        snprintf(out_path, max_len, "/etc/systemd/system");
    } else {
        const char *xdg = getenv("XDG_CONFIG_HOME");
        if (xdg && *xdg) {
            snprintf(out_path, max_len, "%s/systemd/user", xdg);
        } else {
            const char *home = getenv("HOME");
            if (!home || !*home) {
                return -1;
            }
            snprintf(out_path, max_len, "%s/.config/systemd/user", home);
        }
        if (make_dir_p(out_path, 0755) != 0) {
            return -1;
        }
    }
    return 0;
}

int unit_gen_create_service(const AppService *app, char *err_buf, size_t err_len) {
    char dir[MAX_PATH_LEN];
    char file_path[MAX_PATH_LEN];
    FILE *fp;

    if (!app || !is_valid_name(app->name)) {
        if (err_buf) snprintf(err_buf, err_len, "Invalid app name: '%s'", app ? app->name : "NULL");
        return -1;
    }

    if (unit_gen_get_dir(app->scope, dir, sizeof(dir)) != 0) {
        if (err_buf) snprintf(err_buf, err_len, "Failed to resolve systemd unit directory");
        return -1;
    }

    snprintf(file_path, sizeof(file_path), "%s/%s%s.service", dir, FIRE_UNIT_PREFIX, app->name);

    fp = fopen(file_path, "w");
    if (!fp) {
        if (err_buf) snprintf(err_buf, err_len, "Cannot open '%s' for writing: %s", file_path, strerror(errno));
        return -1;
    }

    fprintf(fp, "# Generated by fire-dash v%s\n", FIRE_VERSION);
    fprintf(fp, "[Unit]\n");
    fprintf(fp, "Description=fire-dash service: %s\n", app->name);
    fprintf(fp, "After=network.target\n\n");

    fprintf(fp, "[Service]\n");
    fprintf(fp, "Type=simple\n");
    if (app->cwd[0]) {
        fprintf(fp, "WorkingDirectory=%s\n", app->cwd);
    }
    fprintf(fp, "ExecStart=%s\n", app->script);
    fprintf(fp, "Restart=always\n");
    fprintf(fp, "RestartSec=%d\n", app->restart_sec > 0 ? app->restart_sec : 2);
    fprintf(fp, "StandardOutput=journal\n");
    fprintf(fp, "StandardError=journal\n");

    for (int i = 0; i < app->env_count; i++) {
        fprintf(fp, "Environment=\"%s=%s\"\n", app->envs[i].key, app->envs[i].value);
    }

    fprintf(fp, "\n[Install]\n");
    fprintf(fp, "WantedBy=default.target\n");

    fclose(fp);
    chmod(file_path, 0644);
    return 0;
}

int unit_gen_create_path(const AppService *app, char *err_buf, size_t err_len) {
    char dir[MAX_PATH_LEN];
    char file_path[MAX_PATH_LEN];
    FILE *fp;

    if (!app || !app->watch[0]) return 0; /* Nothing to create */

    if (!is_valid_name(app->name)) {
        if (err_buf) snprintf(err_buf, err_len, "Invalid app name: '%s'", app->name);
        return -1;
    }

    if (unit_gen_get_dir(app->scope, dir, sizeof(dir)) != 0) {
        if (err_buf) snprintf(err_buf, err_len, "Failed to resolve systemd unit directory");
        return -1;
    }

    snprintf(file_path, sizeof(file_path), "%s/%s%s.path", dir, FIRE_UNIT_PREFIX, app->name);

    fp = fopen(file_path, "w");
    if (!fp) {
        if (err_buf) snprintf(err_buf, err_len, "Cannot open '%s' for writing: %s", file_path, strerror(errno));
        return -1;
    }

    fprintf(fp, "# Generated by fire-dash v%s\n", FIRE_VERSION);
    fprintf(fp, "[Unit]\n");
    fprintf(fp, "Description=fire-dash watch trigger for %s\n\n", app->name);

    fprintf(fp, "[Path]\n");
    fprintf(fp, "PathModified=%s\n", app->watch);
    fprintf(fp, "Unit=%s%s.service\n\n", FIRE_UNIT_PREFIX, app->name);

    fprintf(fp, "[Install]\n");
    fprintf(fp, "WantedBy=default.target\n");

    fclose(fp);
    chmod(file_path, 0644);
    return 0;
}

int unit_gen_delete(const char *name, SystemdScope scope, char *err_buf, size_t err_len) {
    char dir[MAX_PATH_LEN];
    char service_path[MAX_PATH_LEN];
    char path_path[MAX_PATH_LEN];

    if (!name || !is_valid_name(name)) {
        if (err_buf) snprintf(err_buf, err_len, "Invalid name: '%s'", name ? name : "NULL");
        return -1;
    }

    if (unit_gen_get_dir(scope, dir, sizeof(dir)) != 0) {
        if (err_buf) snprintf(err_buf, err_len, "Failed to resolve unit directory");
        return -1;
    }

    snprintf(service_path, sizeof(service_path), "%s/%s%s.service", dir, FIRE_UNIT_PREFIX, name);
    snprintf(path_path, sizeof(path_path), "%s/%s%s.path", dir, FIRE_UNIT_PREFIX, name);

    unlink(service_path);
    unlink(path_path);
    return 0;
}

int unit_gen_list_names(SystemdScope scope, char ***out_names, int *out_count) {
    char dir_path[MAX_PATH_LEN];
    DIR *dir;
    struct dirent *entry;
    char **names = NULL;
    int count = 0;
    size_t prefix_len = strlen(FIRE_UNIT_PREFIX);

    if (!out_names || !out_count) return -1;
    *out_names = NULL;
    *out_count = 0;

    if (unit_gen_get_dir(scope, dir_path, sizeof(dir_path)) != 0) {
        return -1;
    }

    dir = opendir(dir_path);
    if (!dir) {
        return 0; /* Empty or non-existent yet */
    }

    while ((entry = readdir(dir)) != NULL) {
        size_t len = strlen(entry->d_name);
        if (len > prefix_len + 8 &&
            strncmp(entry->d_name, FIRE_UNIT_PREFIX, prefix_len) == 0 &&
            strcmp(entry->d_name + len - 8, ".service") == 0) {

            size_t name_len = len - prefix_len - 8;
            char name_buf[MAX_NAME_LEN];
            if (name_len >= sizeof(name_buf)) continue;

            memcpy(name_buf, entry->d_name + prefix_len, name_len);
            name_buf[name_len] = '\0';

            char **new_names = realloc(names, sizeof(char *) * (count + 1));
            if (!new_names) {
                closedir(dir);
                unit_gen_free_names(names, count);
                return -1;
            }
            names = new_names;
            names[count] = strdup(name_buf);
            count++;
        }
    }

    closedir(dir);
    *out_names = names;
    *out_count = count;
    return 0;
}

void unit_gen_free_names(char **names, int count) {
    if (!names) return;
    for (int i = 0; i < count; i++) {
        free(names[i]);
    }
    free(names);
}

bool unit_gen_has_watch(const char *name, SystemdScope scope, char *out_watch_path, size_t max_len) {
    char dir[MAX_PATH_LEN];
    char file_path[MAX_PATH_LEN];
    FILE *fp;
    char line[512];

    if (out_watch_path && max_len > 0) out_watch_path[0] = '\0';
    if (!name || unit_gen_get_dir(scope, dir, sizeof(dir)) != 0) return false;

    snprintf(file_path, sizeof(file_path), "%s/%s%s.path", dir, FIRE_UNIT_PREFIX, name);
    fp = fopen(file_path, "r");
    if (!fp) return false;

    bool found = false;
    while (fgets(line, sizeof(line), fp)) {
        if (strncmp(line, "PathModified=", 13) == 0) {
            char *val = line + 13;
            size_t l = strlen(val);
            while (l > 0 && (val[l - 1] == '\r' || val[l - 1] == '\n' || val[l - 1] == ' ')) {
                val[--l] = '\0';
            }
            if (out_watch_path && max_len > 0) {
                snprintf(out_watch_path, max_len, "%s", val);
            }
            found = true;
            break;
        }
    }
    fclose(fp);
    return found;
}
